import type { Profile } from "./types";
import { DEFAULT_REMINDER_PREFS } from "./types";
import { normalizeProfile } from "./storage";

const base = {
  updatedAt: "2026-08-16T00:00:00.000Z",
  reminderPrefs: { ...DEFAULT_REMINDER_PREFS },
};

export const SAMPLE_PROFILES: { id: string; title: string; blurb: string; profile: Profile }[] = [
  {
    id: "skilled-worker-mid",
    title: "Skilled Worker",
    blurb: "Sponsored since 2024. ILR in 2029, then citizenship.",
    profile: normalizeProfile({
      ...base,
      id: "sample-sw",
      pathwayId: "skilled-worker",
      currentVisaId: "skilled-worker",
      visaGrantedOn: "2024-03-01",
      visaExpiresOn: "2029-03-01",
      qualifyingResidenceStart: "2024-03-01",
      ukEntryDate: "2024-03-01",
      absences: [
        { id: "t1", departedOn: "2025-12-20", returnedOn: "2026-01-10", place: "India" },
      ],
      englishStatus: "b1_or_higher",
      lifeInUkStatus: "not_taken",
      nationality: "IN",
      sponsorshipOverThreeYears: true,
      checkedDocumentIds: ["passport", "evisa"],
    }),
  },
  {
    id: "family-partner",
    title: "Partner visa",
    blurb: "Five-year family route with a British spouse.",
    profile: normalizeProfile({
      ...base,
      id: "sample-spouse",
      pathwayId: "family",
      currentVisaId: "spouse-5",
      visaGrantedOn: "2023-06-15",
      visaExpiresOn: "2026-01-15",
      qualifyingResidenceStart: "2023-06-15",
      ukEntryDate: "2023-06-15",
      englishStatus: "not_met",
      lifeInUkStatus: "not_taken",
      nationality: "PH",
      marriedToBritishCitizen: true,
      hasSettledPartner: true,
      applyFromInsideUk: true,
      checkedDocumentIds: ["passport", "relationship"],
    }),
  },
  {
    id: "student-path",
    title: "Student → Graduate",
    blurb: "On a Graduate visa; Skilled Worker switch still needed for ILR.",
    profile: normalizeProfile({
      ...base,
      id: "sample-grad",
      pathwayId: "student-to-skilled",
      currentVisaId: "graduate",
      visaGrantedOn: "2025-09-01",
      visaExpiresOn: "2027-09-01",
      qualifyingResidenceStart: "2025-09-01",
      ukEntryDate: "2022-09-15",
      priorStages: [{ visaId: "student", start: "2022-09-15", end: "2025-09-01" }],
      plannedSwitchOn: "2027-03-01",
      plannedSwitchTo: "skilled-worker",
      englishStatus: "degree_taught_in_english",
      lifeInUkStatus: "not_taken",
      nationality: "NG",
      applyFromInsideUk: true,
    }),
  },
  {
    id: "global-talent",
    title: "Global Talent",
    blurb: "Exceptional talent endorsement — 3-year ILR clock.",
    profile: normalizeProfile({
      ...base,
      id: "sample-gt",
      pathwayId: "global-talent",
      currentVisaId: "global-talent-talent",
      visaGrantedOn: "2025-01-10",
      visaExpiresOn: "2030-01-10",
      qualifyingResidenceStart: "2025-01-10",
      ukEntryDate: "2025-01-10",
      englishStatus: "b1_or_higher",
      lifeInUkStatus: "not_taken",
      nationality: "US",
    }),
  },
  {
    id: "long-residence",
    title: "10-year long residence",
    blurb: "Mixed lawful leave counting toward a 10-year ILR application.",
    profile: normalizeProfile({
      ...base,
      id: "sample-lr",
      pathwayId: "long-residence",
      currentVisaId: "skilled-worker",
      visaGrantedOn: "2024-01-01",
      visaExpiresOn: "2027-01-01",
      qualifyingResidenceStart: "2018-09-01",
      ukEntryDate: "2018-09-01",
      priorStages: [
        { visaId: "student", start: "2018-09-01", end: "2022-09-01" },
        { visaId: "graduate", start: "2022-09-01", end: "2024-01-01" },
      ],
      englishStatus: "degree_taught_in_english",
      lifeInUkStatus: "passed",
      nationality: "CN",
      applyFromInsideUk: true,
    }),
  },
];

/** Extra scenarios beyond the five featured samples — used by engine tests and the dashboard loader. */
export const EXTRA_SCENARIO_PROFILES: { id: string; title: string; blurb: string; profile: Profile }[] = [
  {
    id: "innovator-founder",
    title: "Innovator Founder",
    blurb: "3-year ILR clock if the business is endorsed for settlement.",
    profile: normalizeProfile({
      ...base,
      id: "sample-innovator",
      pathwayId: "innovator-founder",
      currentVisaId: "innovator-founder",
      visaGrantedOn: "2025-01-01",
      visaExpiresOn: "2028-01-01",
      qualifyingResidenceStart: "2025-01-01",
      ukEntryDate: "2025-01-01",
      englishStatus: "b1_or_higher",
      nationality: "IN",
    }),
  },
  {
    id: "switch-chain",
    title: "Student → Skilled Worker → Global Talent",
    blurb: "Multiple planned switches; the Global Talent 3-year clock starts on that grant.",
    profile: normalizeProfile({
      ...base,
      id: "sample-chain",
      pathwayId: "student-to-skilled",
      currentVisaId: "student",
      visaGrantedOn: "2024-09-01",
      visaExpiresOn: "2027-09-01",
      qualifyingResidenceStart: "2024-09-01",
      ukEntryDate: "2024-09-01",
      plannedSwitches: [
        { toVisaId: "skilled-worker", on: "2027-09-01" },
        { toVisaId: "global-talent-talent", on: "2028-09-01" },
      ],
      englishStatus: "degree_taught_in_english",
      nationality: "NG",
    }),
  },
  {
    id: "mixed-long-residence",
    title: "Student + Graduate + Skilled Worker (10-year mix)",
    blurb: "Lawful time on study then work combining toward long residence.",
    profile: normalizeProfile({
      ...base,
      id: "sample-mix",
      pathwayId: "skilled-worker",
      currentVisaId: "skilled-worker",
      visaGrantedOn: "2024-01-01",
      visaExpiresOn: "2027-01-01",
      qualifyingResidenceStart: "2024-01-01",
      ukEntryDate: "2016-09-01",
      priorStages: [
        { visaId: "student", start: "2016-09-01", end: "2022-09-01" },
        { visaId: "graduate", start: "2022-09-01", end: "2024-01-01" },
      ],
      englishStatus: "degree_taught_in_english",
      lifeInUkStatus: "passed",
      nationality: "CN",
    }),
  },
  {
    id: "child-uk-birth",
    title: "Child born in the UK",
    blurb: "Registration after a parent becomes settled (section 1(3)).",
    profile: normalizeProfile({
      ...base,
      id: "sample-child",
      pathwayId: "child-registration",
      currentVisaId: "child-registration",
      visaGrantedOn: "2024-03-01",
      visaExpiresOn: "2029-03-01",
      qualifyingResidenceStart: "2024-03-01",
      ukEntryDate: "2024-03-01",
      ageBand: "under_18",
      bornInUk: true,
      hasBritishParent: false,
      mainApplicantIlrOn: "2029-03-01",
      nationality: "IN",
    }),
  },
  {
    id: "dependant-partner",
    title: "Partner dependant",
    blurb: "Dependant ILR after 5 years, aligned with the main applicant.",
    profile: normalizeProfile({
      ...base,
      id: "sample-dep",
      pathwayId: "dependant",
      currentVisaId: "dependant",
      visaGrantedOn: "2024-03-01",
      visaExpiresOn: "2027-03-01",
      qualifyingResidenceStart: "2024-03-01",
      ukEntryDate: "2024-03-01",
      mainApplicantIlrOn: "2029-03-01",
      englishStatus: "b1_or_higher",
      nationality: "PH",
    }),
  },
];
