import type { Profile } from "./types";
import { DEFAULT_REMINDER_PREFS } from "./types";

export const SAMPLE_PROFILES: { id: string; title: string; blurb: string; profile: Profile }[] = [
  {
    id: "skilled-worker-mid",
    title: "Skilled Worker, two years in",
    blurb: "Sponsored role since 2024, some travel, tests still to book.",
    profile: {
      id: "sample-sw",
      updatedAt: "2026-08-16T00:00:00.000Z",
      currentVisaId: "skilled-worker",
      visaGrantedOn: "2024-03-01",
      visaExpiresOn: "2029-03-01",
      qualifyingResidenceStart: "2024-03-01",
      ukEntryDate: "2024-03-01",
      daysAbsentLast12Months: 21,
      exceeded180DaysInAny12Months: false,
      daysAbsentLast5Years: 45,
      daysAbsentLast12MonthsCitizenship: 21,
      englishStatus: "b1_or_higher",
      lifeInUkStatus: "not_taken",
      nationality: "IN",
      ageBand: "18_to_64",
      marriedToBritishCitizen: false,
      hasSettledPartner: false,
      reminderPrefs: { ...DEFAULT_REMINDER_PREFS },
      checkedDocumentIds: ["passport", "evisa"],
    },
  },
  {
    id: "graduate-switch",
    title: "Graduate visa, needs a switch",
    blurb: "Post-study leave that does not lead to ILR — compare work and talent options.",
    profile: {
      id: "sample-grad",
      updatedAt: "2026-08-16T00:00:00.000Z",
      currentVisaId: "graduate",
      visaGrantedOn: "2025-09-01",
      visaExpiresOn: "2027-09-01",
      qualifyingResidenceStart: "2025-09-01",
      ukEntryDate: "2022-09-15",
      daysAbsentLast12Months: 12,
      exceeded180DaysInAny12Months: false,
      daysAbsentLast5Years: 80,
      daysAbsentLast12MonthsCitizenship: 12,
      englishStatus: "degree_taught_in_english",
      lifeInUkStatus: "not_taken",
      nationality: "NG",
      ageBand: "18_to_64",
      marriedToBritishCitizen: false,
      hasSettledPartner: false,
      reminderPrefs: { ...DEFAULT_REMINDER_PREFS },
      checkedDocumentIds: [],
    },
  },
  {
    id: "spouse-british",
    title: "Partner of a British citizen",
    blurb: "Five-year family route, with the shorter citizenship wait after ILR.",
    profile: {
      id: "sample-spouse",
      updatedAt: "2026-08-16T00:00:00.000Z",
      currentVisaId: "spouse-5",
      visaGrantedOn: "2023-06-15",
      visaExpiresOn: "2026-01-15",
      qualifyingResidenceStart: "2023-06-15",
      ukEntryDate: "2023-06-15",
      daysAbsentLast12Months: 18,
      exceeded180DaysInAny12Months: false,
      daysAbsentLast5Years: 40,
      daysAbsentLast12MonthsCitizenship: 18,
      englishStatus: "not_met",
      lifeInUkStatus: "not_taken",
      nationality: "PH",
      ageBand: "18_to_64",
      marriedToBritishCitizen: true,
      hasSettledPartner: true,
      reminderPrefs: { ...DEFAULT_REMINDER_PREFS },
      checkedDocumentIds: ["passport", "relationship"],
    },
  },
];
